name: Publish to NPM

on:
    pull_request:
        types:
            - closed
        branches:
            - main

jobs:
    test:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install dependencies
              run: yarn install

            - name: Run tests
              run: yarn test

            - name: Bump version
              id: package
              run: |
                  if [[ "${{ github.head_ref }}" == feature/* ]]; then
                    yarn version --minor
                  elif [[ "${{ github.head_ref }}" == bugfix/* ]]; then
                    yarn version --patch
                  fi

            - name: Commit version increment
              uses: EndBug/add-and-commit@v9
              with:
                  add: "package.json"
                  message: "[auto-commit] Increment version number"
                  pull: "--rebase --autostash"
                  default_author: github_actions

            - name: Publish to NPM
              run: yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
