name: Generate documentation

on:
    push:
        branches:
            - main
            - feature/*

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install dependencies
              run: yarn install

            - name: Generate documentation
              run: yarn docs

            - name: Deploy to docs branch
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: docs
                  publish_dir: ./docs/final
